[versions]
androidGradlePlugin = "8.10.1"
androidxActivity = "1.10.1"
androidxCore = "1.16.0"
cashLicensee = "1.13.0"
cashMolecule = "2.0.0"
cashTurbine = "1.2.0"
harawataAppdirs = "1.4.0"
jetbrainsCompose = "1.8.1"
jetbrainsComposeMaterialIconsCore = "1.7.3"
kotlin = "2.2.20"
kotlinxCoroutines = "1.10.2"
kotlinxIo = "0.8.0"
kotlinxSerialization = "1.9.0"

[libraries]
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCore" }
cashMolecule = { module = "app.cash.molecule:molecule-runtime", version.ref = "cashMolecule" }
cashTurbine = { module = "app.cash.turbine:turbine", version.ref = "cashTurbine" }
harawataAppdirs = { module = "net.harawata:appdirs", version.ref = "harawataAppdirs" }
jetbrainsComposeMaterialIconsCore = { module = "org.jetbrains.compose.material:material-icons-core", version.ref = "jetbrainsComposeMaterialIconsCore" }
jetbrainsComposeUiBackhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "jetbrainsCompose" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinxIoCore = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinxIo" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxSerializationJsonIo = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json-io", version.ref = "kotlinxSerialization" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
cashLicensee = { id = "app.cash.licensee", version.ref = "cashLicensee" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "jetbrainsCompose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
