import app.cash.licensee.LicenseeTask
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilation
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType
import org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardCopyOption

plugins {
    alias libs.plugins.androidApplication
    alias libs.plugins.cashLicensee
    alias libs.plugins.composeCompiler
    alias libs.plugins.jetbrainsCompose
    alias libs.plugins.kotlinMultiplatform
    alias libs.plugins.kotlinSerialization
}

tasks.withType(KotlinJvmCompile).configureEach {
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11.toString()
    }
}

kotlin {
    androidTarget()
    jvm("desktop")

    wasmJs {
        outputModuleName = "composeApp"
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation compose.components.resources
                implementation compose.material
                implementation compose.ui
                implementation libs.jetbrainsComposeUiBackhandler
                implementation libs.jetbrainsSavedstate
                implementation libs.kotlinxCoroutinesCore
                implementation libs.kotlinxSerializationJson
            }
        }

        jvmAndroidMain {
            dependsOn(commonMain)
            dependencies {
                implementation libs.kotlinxIoCore
                implementation libs.kotlinxSerializationJsonIo
            }
        }

        androidMain {
            dependsOn(jvmAndroidMain)
            dependencies {
                implementation libs.androidxActivityCompose
                implementation libs.androidxCoreKtx
            }
        }

        desktopMain {
            dependsOn(jvmAndroidMain)
            dependencies {
                implementation compose.desktop.currentOs
                implementation libs.harawataAppdirs
            }
        }

        wasmJsMain {
            dependsOn(commonMain)
        }

        commonTest {
            dependencies {
                implementation libs.cashMolecule
                implementation libs.cashTurbine
                implementation libs.kotlinTest
                implementation libs.kotlinxCoroutinesTest
            }
        }
    }
}

android {
    compileSdk 35
    namespace "com.alexjlockwood.twentyfortyeightcompose"

    defaultConfig {
        applicationId "com.alexjlockwood.twentyfortyeightcompose"
        minSdk 26 // A minimal available API for java.nio.Files atomic movement.
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        debug {
            storeFile file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.named("debug").get()
        }
    }

    buildFeatures {
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

compose {
    desktop {
        application {
            mainClass = "MainKt"

            nativeDistributions {
                targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
                packageName = "com.alexjlockwood.twentyfortyeightcompose"
                packageVersion = "1.0.0"
            }
        }
    }

    experimental {
        web.application {}
    }

    resources {
        packageOfResClass "com.alexjlockwood.twentyfortyeight"

        kotlin.targets.configureEach { target ->
            if (target.platformType == KotlinPlatformType.common) {
                return
            }
            if (target.platformType == KotlinPlatformType.androidJvm) {
                androidComponents {
                    onVariants(selector().all()) { variant ->
                        String suffix = "${target.name}${replaceFirstCharWithUpperCase(variant.name)}"
                        customDirectory(suffix, licenseeResourcesDirectory(suffix, provider { variant.runtimeConfiguration }))
                    }
                }
            } else {
                String compilationName = KotlinCompilation.MAIN_COMPILATION_NAME
                String suffix = "${target.name}${replaceFirstCharWithUpperCase(compilationName)}"
                Provider<Configuration> configuration = target.compilations.named(compilationName).map { compilation ->
                    String configurationName = compilation.runtimeDependencyConfigurationName
                    if (configurationName != null) {
                        configurations.named(configurationName).get()
                    } else {
                        configurations.named(compilation.compileDependencyConfigurationName).get()
                    }
                }
                customDirectory(suffix, licenseeResourcesDirectory(suffix, configuration))
            }
        }
    }
}

licensee {
    allow "Apache-2.0"
}

private static String replaceFirstCharWithUpperCase(String input) {
    return input.substring(0,1).toUpperCase() + input.substring(1)
}

private Provider<Directory> licenseeResourcesDirectory(String suffix, Provider<Configuration> configuration) {
    return tasks.register("licenseeGenerateResources${replaceFirstCharWithUpperCase(suffix)}", LicenseeTask) {
        configurationToCheck configuration.get()
        outputDir.set(layout.projectDirectory.dir(Paths.get("reports", "licensee", suffix).toString()))
        doLast {
            Path from = Paths.get(layout.projectDirectory.toString(), "reports", "licensee", suffix, "artifacts.json")
            Path to = Paths.get(layout.buildDirectory.get().toString(), "generated", "licensee", suffix, "files", "artifacts.json")
            if (!Files.exists(to.parent)) {
                Files.createDirectories(to.parent)
            }
            Files.move(from, to, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING)
        }
    }.map {
        layout.buildDirectory.get().dir(Paths.get("generated", "licensee", suffix).toString())
    }
}
