import app.cash.licensee.LicenseeTask
import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.plugin.KotlinCompilation
import org.jetbrains.kotlin.gradle.plugin.KotlinPlatformType
import java.nio.file.Paths

plugins {
    alias libs.plugins.androidApplication
    alias libs.plugins.cashLicensee
    alias libs.plugins.composeCompiler
    alias libs.plugins.jetbrainsCompose
    alias libs.plugins.kotlinMultiplatform
    alias libs.plugins.kotlinSerialization
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    jvm("desktop")

    js {
        outputModuleName.set("composeApp")
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
        }
        binaries {
            executable()
        }
        useEsModules()
    }

    wasmJs {
        outputModuleName.set("composeApp")
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
        }
        binaries {
            executable()
        }
    }

    sourceSets {
        commonMain {
            dependencies {
                implementation libs.jetbrainsComposeComponentsResources
                implementation libs.jetbrainsComposeMaterial
                implementation libs.jetbrainsComposeMaterialIconsCore
                implementation libs.jetbrainsComposeUi
                implementation libs.jetbrainsNavigationEventCompose
                implementation libs.kotlinxCoroutinesCore
                implementation libs.kotlinxSerializationJson
            }
        }

        jvmAndroidMain {
            dependsOn(commonMain)
            dependencies {
                implementation libs.kotlinxIoCore
                implementation libs.kotlinxSerializationJsonIo
            }
        }

        androidMain {
            dependsOn(jvmAndroidMain)
            dependencies {
                implementation libs.androidxActivityCompose
                implementation libs.androidxCoreKtx
            }
        }

        desktopMain {
            dependsOn(jvmAndroidMain)
            dependencies {
                implementation compose.desktop.currentOs
                implementation libs.harawataAppdirs
            }
        }

        webMain {
            dependsOn(commonMain)
            dependencies {
                implementation libs.kotlinxBrowser
            }
        }

        jsMain {
            dependsOn(webMain)
        }

        wasmJsMain {
            dependsOn(webMain)
        }

        commonTest {
            dependencies {
                implementation libs.cashMolecule
                implementation libs.cashTurbine
                implementation libs.kotlinTest
                implementation libs.kotlinxCoroutinesTest
            }
        }
    }
}

android {
    compileSdk 36
    namespace "com.alexjlockwood.twentyfortyeightcompose"

    defaultConfig {
        applicationId "com.alexjlockwood.twentyfortyeightcompose"
        minSdk 26 // A minimal available API for java.nio.Files atomic movement.
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
    }

    signingConfigs {
        debug {
            storeFile file("debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
        }
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.named("debug").get()
        }
    }

    buildFeatures {
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    testOptions {
        unitTests {
            returnDefaultValues true // for app.cash.molecule
        }
    }
}

compose {
    desktop {
        application {
            mainClass "MainKt"
            nativeDistributions {
                targetFormats TargetFormat.AppImage
                packageName "com.alexjlockwood.twentyfortyeightcompose"
                packageVersion "1.0.0"
            }
        }
    }

    resources {
        packageOfResClass "com.alexjlockwood.twentyfortyeight"
    }
}

kotlin.targets.configureEach { target ->
    if (target.platformType == KotlinPlatformType.common) {
        return
    }
    if (target.platformType == KotlinPlatformType.androidJvm) {
        androidComponents {
            onVariants(selector().all()) { variant ->
                String suffix = "${target.name}${replaceFirstCharWithUpperCase(variant.name)}"
                Configuration configuration = variant.runtimeConfiguration
                Directory outputDir = layout.buildDirectory.get().dir(Paths.get("generated", "licensee", suffix).toString())
                TaskProvider<Task> licenseeTask = licenseeResourcesGenerationTask(suffix, configuration, outputDir)
                compose.resources.customDirectory(suffix, licenseeTask.map { outputDir })
            }
        }
    } else {
        String compilationName = KotlinCompilation.MAIN_COMPILATION_NAME
        String suffix = "${target.name}${replaceFirstCharWithUpperCase(compilationName)}"
        String configurationName = target.compilations.named(compilationName).get().runtimeDependencyConfigurationName
        if (configurationName == null) {
            logger.error("Cannot find ${target.name} runtime configuration.")
            return
        }
        Configuration configuration = configurations.named(configurationName).get()
        Directory outputDir = layout.buildDirectory.get().dir(Paths.get("generated", "licensee", suffix).toString())
        TaskProvider<Task> licenseeTask = licenseeResourcesGenerationTask(suffix, configuration, outputDir)
        compose.resources.customDirectory(suffix, licenseeTask.map { outputDir })
    }
}

licensee {
    allow "Apache-2.0"
}

private static String replaceFirstCharWithUpperCase(String input) {
    return input.substring(0,1).toUpperCase() + input.substring(1)
}

private TaskProvider<LicenseeTask> licenseeResourcesGenerationTask(String suffix, Configuration configuration, Directory outputDir) {
    return tasks.register("generateLicenseeResources${replaceFirstCharWithUpperCase(suffix)}", LicenseeTask) { licenseeTask ->
        configurationToCheck configuration
        doLast {
            copy {
                from licenseeTask.jsonOutput.get()
                into outputDir.dir("files")
                include "**/artifacts.json"
            }
        }
        doLast {
            copy {
                from licenseeTask.validationOutput.get()
                into layout.projectDirectory.dir(Paths.get("reports", "licensee", suffix).toString())
                include "**/validation.txt"
            }
        }
    }
}
