name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains'
          java-version: '17'
          package-type: 'jdk+jcef'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build WasmJs with Gradle
        run: |
          ./gradlew :app:licensee
          ./gradlew :app:copyArtifactsJsonFiles
          ./gradlew :app:wasmJsBrowserDistribution

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/build/dist/wasmJs/productionExecutable

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
