name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'jetbrains'
          java-package: 'jdk+jcef'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build with Gradle
        run: |
          ./gradlew :app:jsBrowserDistribution
          ./gradlew :app:wasmJsBrowserDistribution
          ./gradlew :app:composeCompatibilityBrowserDistribution

      - name: Test with Gradle
        run: |
          ./gradlew :app:jsBrowserTest
          ./gradlew :app:wasmJsBrowserTest

      - name: Organize artifacts
        run: |
          cp -r app/build/dist/composeWebCompatibility/productionExecutable dist
          cp -r app/build/dist/js/productionExecutable dist/js
          cp -r app/build/dist/wasmJs/productionExecutable dist/wasmJs

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
